FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /OrderGenerator

COPY . .
RUN dotnet restore "OrderGenerator.csproj"

RUN dotnet publish "OrderGenerator.csproj" -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /OrderGenerator
COPY --from=build-env /OrderGenerator/out .
ENTRYPOINT ["dotnet", "OrderGenerator.dll"]